export const ISUSERLOGGEDIN='ISUSERLOGGEDIN';
export const USERLOGGEDOUT='USERLOGGEDOUT';

export const ADD_PROFILEDATA='ADD_LAWYERPROFILEDATA';
export const ADD_PROFILEDATA_LOADING='ADD_LAWYERPROFILEDATA_LOADING';
export const ADD_PROFILEDATAFAILED='ADD_LAWYERPROFILEDATAFAILED';

export const ADD_USERURLDATA='ADD_USERURLDATA';
export const ADD_USERURLDATA_LOADING='ADD_USERURLDATA_LOADING';
export const ADD_USERURLDATA_FAILED='ADD_USERURLDATA_FAILED';

export const ERROR_MESSAGE='ERROR_MESSAGE';
export const SUCCESS_MESSAGE='SUCCESS_MESSAGE';
export const CLEAR_MESSAGE='CLEAR_MESSAGE';

export const LOADING='LOADING';
export const CLEAR_LOADING='CLEAR_LOADING';